# -*- coding: utf-8 -*-
"""Advancing BERT: Fine-Tuning Inefficiency using LoRA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gtj6S5wtrH3jRepGpIUIURE6Jm4WyLze
"""



"""# Advancing BERT: A Research-Oriented NLP Programming Assignment 2 (CSE 39)

Part 4: Fine-Tuning Inefficiency (Roll Numbers Ending with 3 and 8 Only)

Problem: Full fine-tuning of BERT is computationally expensive.

Objective: Implement parameter-efficient fine-tuning.

Tasks:
- Implement:
– LoRA (Low-Rank Adaptation)
– Adapter layers
- Compare with full fine-tuning

Extensions:
- Freeze selective layers
- Train only attention layers
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install transformers datasets peft accelerate scikit-learn

import torch
from datasets import load_dataset
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from sklearn.metrics import accuracy_score, f1_score

dataset = load_dataset("imdb")

train_data = dataset["train"]
test_data = dataset["test"]

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

def tokenize(example):
    return tokenizer(example["text"], padding="max_length", truncation=True, max_length=256)

train_data = train_data.map(tokenize, batched=True)
test_data = test_data.map(tokenize, batched=True)

train_data.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])
test_data.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])

lengths = [len(x["input_ids"]) for x in train_data]
print("Max length:", max(lengths))
print("Min length:", min(lengths))
print("Average length:", sum(lengths)/len(lengths))

def compute_metrics(pred):
    logits, labels = pred
    preds = torch.argmax(torch.tensor(logits), axis=1)
    acc = accuracy_score(labels, preds)
    f1 = f1_score(labels, preds)
    return {"accuracy": acc, "f1": f1}

def count_parameters(model):
    return sum(p.numel() for p in model.parameters())

def count_trainable_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

from transformers import BertForSequenceClassification, Trainer, TrainingArguments
import time

model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)

training_args = TrainingArguments(
    output_dir="./baseline",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=1,
    eval_strategy="epoch",
    save_strategy="no",
    logging_steps=100
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_data,
    eval_dataset=test_data,
    compute_metrics=compute_metrics
)

start_time = time.time()

trainer.train()

end_time = time.time()
baseline_time = end_time - start_time

baseline_result = trainer.evaluate()
baseline_params = count_parameters(model)

from peft import LoraConfig, get_peft_model, TaskType

model_lora = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)

lora_config = LoraConfig(
    task_type=TaskType.SEQ_CLS,
    r=8,
    lora_alpha=16,
    lora_dropout=0.1
)

model_lora = get_peft_model(model_lora, lora_config)

training_args_lora = TrainingArguments(
    output_dir="./lora",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=1,
    eval_strategy="epoch",
    save_strategy="no",
    logging_steps=100
)

trainer_lora = Trainer(
    model=model_lora,
    args=training_args_lora,
    train_dataset=train_data,
    eval_dataset=test_data,
    compute_metrics=compute_metrics
)

start_time = time.time()

trainer_lora.train()

end_time = time.time()
lora_time = end_time - start_time

lora_result = trainer_lora.evaluate()

lora_total_params = count_parameters(model_lora)
lora_trainable_params = count_trainable_parameters(model_lora)

print("\nBaseline Model")
print("Accuracy:", baseline_result["eval_accuracy"])
print("F1 Score:", baseline_result["eval_f1"])
print("Training Time (sec):", baseline_time)
print("Training Time (min):", baseline_time/60)
print("Total Parameters:", baseline_params)

print("\nLoRA Model")
print("Accuracy:", lora_result["eval_accuracy"])
print("F1 Score:", lora_result["eval_f1"])
print("Training Time (sec):", lora_time)
print("Training Time (min):", lora_time/60)
print("Total Parameters:", lora_total_params)
print("Trainable Parameters:", lora_trainable_params)

import matplotlib.pyplot as plt

models = ["Baseline", "LoRA"]
accuracy = [baseline_result["eval_accuracy"], lora_result["eval_accuracy"]]

plt.figure(figsize=(6,4))
plt.bar(models, accuracy)
plt.title("Accuracy Comparison")
plt.xlabel("Model")
plt.ylabel("Accuracy")
plt.show()

f1_scores = [baseline_result["eval_f1"], lora_result["eval_f1"]]

plt.figure(figsize=(6,4))
plt.bar(models, f1_scores)
plt.title("F1 Score Comparison")
plt.xlabel("Model")
plt.ylabel("F1 Score")
plt.show()

times = [baseline_time, lora_time]

plt.figure(figsize=(6,4))
plt.bar(models, times)
plt.title("Training Time Comparison (seconds)")
plt.xlabel("Model")
plt.ylabel("Time")
plt.show()

